modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="ae2additions"
version="${version}"
displayName="AE2 Additions"
credits="Thanks for this example mod goes to Java"
authors="SerStarStory"
description='''Some generic mod'''

[[dependencies.ae2additions]]
modId = "forge"
mandatory = true
versionRange = "[40.0.0,41.0.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ae2additions]]
modId = "ae2"
mandatory = true
versionRange = "[11.1.1,12.0.0)"
ordering = "AFTER"
side = "BOTH"
